In [3]:
df = pd.read_csv("datas/master_table.csv")

In [1]:
df.head()

NameError: name 'df' is not defined

In [5]:
df.isnull().sum()

year            0
month           0
quarter         0
WeekDay         0
Weekend         0
Home            1
Result          3
Away            0
etc             0
Time          100
Park            0
Shiny           0
Rain            0
Min_c           0
Max_c           0
NO2            45
O3             45
CO             45
SO2            45
PM10           45
PM25           45
attendance      0
dtype: int64

In [6]:
df = df.fillna(value = 0)

In [7]:
df.tail()

,year,month,quarter,WeekDay,Weekend,Home,Result,Away,etc,Time,...,Rain,Min_c,Max_c,NO2,O3,CO,SO2,PM10,PM25,attendance
411,2019,9,3,금,1,두산,win,KIA,-,13:30,...,1.0,18.0,29.0,0.013,0.028,0.3,0.002,11.0,5.0,12415
412,2019,9,3,일,1,LG,lose,SK,-,18:30,...,0.0,20.0,30.0,0.012,0.029,0.5,0.002,13.0,8.0,18171
413,2019,9,3,월,0,0,LG,SK<span,-,18:30,...,0.0,21.0,31.0,0.018,0.022,0.4,0.002,10.0,5.0,9298
414,2019,9,3,금,0,두산,lose,롯데,-,17:00,...,0.0,16.0,24.0,0.024,0.014,0.4,0.002,22.0,8.0,13147
415,2019,9,3,화,0,두산,win,삼성,-,18:30,...,0.0,14.0,27.0,0.034,0.016,0.5,0.003,24.0,12.0,15115

In [56]:
df.to_csv("kbo_datas.csv", index=False)

In [10]:
model = sm.OLS.from_formula("attendance ~ C(WeekDay) + C(Weekend) + Shiny + Rain + Min_c + Max_c + NO2 + O3 + CO + SO2 + PM10 + PM25 + C(Away) + C(Home) + C(Result) + C(Time)", data=df)

In [11]:
result = model.fit()

In [12]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             attendance   R-squared:                       0.816
Model:                            OLS   Adj. R-squared:                  0.796
Method:                 Least Squares   F-statistic:                     40.45
Date:                Mon, 09 Dec 2019   Prob (F-statistic):          6.77e-113
Time:                        16:29:04   Log-Likelihood:                -3832.1
No. Observations:                 416   AIC:                             7748.
Df Residuals:                     374   BIC:                             7917.
Df Model:                          41
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept           6877.3693   1149.515      5.983      0.000    4617.047    9137.692
C(WeekDay)[T.목]    -3190.6572    459.616     -6.942      0.000   -4094.412   -2286.903
C(WeekDay)[T.수]    -4150.1833    462.341     -8.976      0.000   -5059.298   -3241.069
C(WeekDay)[T.월]    -1042.8408    854.836     -1.220      0.223   -2723.728     638.046
C(WeekDay)[T.일]    -4480.2673    852.410     -5.256      0.000   -6156.385   -2804.150
C(WeekDay)[T.토]    -1019.8167    929.376     -1.097      0.273   -2847.275     807.641
C(WeekDay)[T.화]    -3660.7199    459.890     -7.960      0.000   -4565.014   -2756.426
C(Weekend)[T.1]     6290.2756    833.249      7.549      0.000    4651.835    7928.716
C(Away)[T.KT]      -5266.4397   1448.783     -3.635      0.000   -8115.220   -2417.659
C(Away)[T.LG]       1923.4943   1475.301      1.304      0.193    -977.429    4824.418
C(Away)[T.NC]      -3944.5262   1440.598     -2.738      0.006   -6777.212   -1111.840
C(Away)[T.SK]      -2987.1286   1424.826     -2.096      0.037   -5788.804    -185.454
C(Away)[T.SK<span] -1042.8408    854.836     -1.220      0.223   -2723.728     638.046
C(Away)[T.기아]       3948.0437   1458.019      2.708      0.007    1081.100    6814.987
C(Away)[T.넥센]      -4511.0900   1470.813     -3.067      0.002   -7403.189   -1618.991
C(Away)[T.두산]       1866.0399   1469.504      1.270      0.205   -1023.486    4755.566
C(Away)[T.롯데]       1008.2675   1418.694      0.711      0.478   -1781.350    3797.885
C(Away)[T.삼성]       -857.5477   1432.460     -0.599      0.550   -3674.232    1959.137
C(Away)[T.키움]      -4213.2114   1656.974     -2.543      0.011   -7471.364    -955.059
C(Away)[T.한화]       1667.0689   1450.306      1.149      0.251   -1184.707    4518.845
C(Away)[T.히어로즈]     -572.6713   1954.988     -0.293      0.770   -4416.818    3271.475
C(Home)[T.LG]       4121.1234    797.070      5.170      0.000    2553.822    5688.424
C(Home)[T.두산]       3799.0868    793.521      4.788      0.000    2238.764    5359.409
C(Result)[T.LG]    -1042.8408    854.836     -1.220      0.223   -2723.728     638.046
C(Result)[T.lose]  -2368.6617   1370.004     -1.729      0.085   -5062.537     325.214
C(Result)[T.win]   -2785.7582   1220.059     -2.283      0.023   -5184.794    -386.722
C(Result)[T.무]      -321.4246   2029.677     -0.158      0.874   -4312.435    3669.585
C(Result)[T.승]       129.4861   1670.112      0.078      0.938   -3154.501    3413.474
C(Result)[T.패]      -269.9095   1664.990     -0.162      0.871   -3543.825    3004.006
C(Time)[T. 13:30 ] -5761.2345   2604.499     -2.212      0.028   -1.09e+04    -639.937
C(Time)[T. 17:00 ] -1811.5223   1122.715     -1.614      0.107   -4019.147     396.102
C(Time)[T. 18:30 ]  1375.4961   1060.813      1.297      0.196    -710.409    3461.402
C(Time)[T.14:00]    3711.7065    702.783      5.281      0.000    2329.805    5093.608
C(Time)[T.17:00]    1113.6701    702.899      1.584      0.114    -268.459    2495.799
C(Time)[T.18:00]     854.1572    814.775      1.048      0.295    -747.956    2456.271
C(Time)[T.18:30]    2051.5950    535.640      3.830      0.000     998.352    3104.838
C(Time)[T.19:00]    4299.2324   2658.573      1.617      0.107    -928.392    9526.857
Shiny               3656.8113    634.927      5.759      0.000    2408.338    4905.285
Rain                3220.5580    561.279      5.738      0.000    2116.899    4324.217
Min_c               -219.9786     60.474     -3.638      0.000    -338.889    -101.068
Max_c                182.1034     62.417      2.918      0.004      59.371     304.836
NO2                 4.746e+04   2.81e+04      1.689      0.092   -7799.190    1.03e+05
O3                 -5903.5194   1.47e+04     -0.402      0.688   -3.48e+04     2.3e+04
CO                 -2397.9825   1329.645     -1.803      0.072   -5012.499     216.534
SO2                -1.833e+05   1.81e+05     -1.015      0.311   -5.39e+05    1.72e+05
PM10                  -4.9710      9.937     -0.500      0.617     -24.511      14.569
PM25                  28.4941     22.744      1.253      0.211     -16.227      73.216
==============================================================================
Omnibus:                        6.298   Durbin-Watson:                   1.518
Prob(Omnibus):                  0.043   Jarque-Bera (JB):                7.562
Skew:                           0.158   Prob(JB):                       0.0228
Kurtosis:                       3.580   Cond. No.                     1.71e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.13e-27. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [14]:
model2 = sm.OLS.from_formula("attendance ~ C(WeekDay) + C(Weekend) + Shiny + Rain + C(Away) + C(Home) + C(Result) + C(Time)", data=df)
result2 = model2.fit()
print(result2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             attendance   R-squared:                       0.799
Model:                            OLS   Adj. R-squared:                  0.781
Method:                 Least Squares   F-statistic:                     45.93
Date:                Mon, 09 Dec 2019   Prob (F-statistic):          2.80e-112
Time:                        16:29:26   Log-Likelihood:                -3850.8
No. Observations:                 416   AIC:                             7770.
Df Residuals:                     382   BIC:                             7907.
Df Model:                          33
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept           7235.4390   1046.696      6.913      0.000    5177.432    9293.446
C(WeekDay)[T.목]    -3302.0719    471.955     -6.997      0.000   -4230.026   -2374.117
C(WeekDay)[T.수]    -4242.2917    474.173     -8.947      0.000   -5174.608   -3309.976
C(WeekDay)[T.월]    -1178.1316    872.813     -1.350      0.178   -2894.250     537.987
C(WeekDay)[T.일]    -4725.6664    874.304     -5.405      0.000   -6444.718   -3006.615
C(WeekDay)[T.토]    -1077.4257    951.609     -1.132      0.258   -2948.473     793.621
C(WeekDay)[T.화]    -3662.4524    474.498     -7.719      0.000   -4595.407   -2729.498
C(Weekend)[T.1]     6145.4412    847.875      7.248      0.000    4478.356    7812.527
C(Away)[T.KT]      -5511.9114   1478.086     -3.729      0.000   -8418.115   -2605.708
C(Away)[T.LG]       1419.6412   1509.828      0.940      0.348   -1548.972    4388.254
C(Away)[T.NC]      -4149.8402   1478.693     -2.806      0.005   -7057.236   -1242.444
C(Away)[T.SK]      -3219.3827   1453.837     -2.214      0.027   -6077.908    -360.858
C(Away)[T.SK<span] -1178.1316    872.813     -1.350      0.178   -2894.250     537.987
C(Away)[T.기아]       3766.1792   1488.848      2.530      0.012     838.816    6693.542
C(Away)[T.넥센]      -4690.5131   1504.827     -3.117      0.002   -7649.293   -1731.733
C(Away)[T.두산]       1635.5737   1509.626      1.083      0.279   -1332.643    4603.790
C(Away)[T.롯데]        683.7687   1450.819      0.471      0.638   -2168.823    3536.360
C(Away)[T.삼성]      -1139.7167   1464.670     -0.778      0.437   -4019.541    1740.108
C(Away)[T.키움]      -4509.7777   1676.564     -2.690      0.007   -7806.228   -1213.328
C(Away)[T.한화]       1429.6642   1480.489      0.966      0.335   -1481.263    4340.591
C(Away)[T.히어로즈]     -863.0052   2010.585     -0.429      0.668   -4816.204    3090.194
C(Home)[T.LG]       4355.8370    765.710      5.689      0.000    2850.303    5861.371
C(Home)[T.두산]       4057.7336    771.588      5.259      0.000    2540.642    5574.825
C(Result)[T.LG]    -1178.1316    872.813     -1.350      0.178   -2894.250     537.987
C(Result)[T.lose]  -2409.6743   1398.677     -1.723      0.086   -5159.743     340.395
C(Result)[T.win]   -2595.6210   1249.206     -2.078      0.038   -5051.803    -139.439
C(Result)[T.무]       719.0864   2054.484      0.350      0.727   -3320.426    4758.599
C(Result)[T.승]      1134.0381   1663.290      0.682      0.496   -2136.312    4404.388
C(Result)[T.패]       650.7954   1661.748      0.392      0.696   -2616.522    3918.113
C(Time)[T. 13:30 ] -5473.7862   2663.836     -2.055      0.041   -1.07e+04    -236.168
C(Time)[T. 17:00 ] -2116.9508   1151.662     -1.838      0.067   -4381.341     147.440
C(Time)[T. 18:30 ]  1407.3102   1092.448      1.288      0.198    -740.653    3555.274
C(Time)[T.14:00]    3055.2524    632.136      4.833      0.000    1812.350    4298.154
C(Time)[T.17:00]     653.9212    630.561      1.037      0.300    -585.883    1893.725
C(Time)[T.18:00]    -815.6097    681.363     -1.197      0.232   -2155.302     524.082
C(Time)[T.18:30]     930.1145    393.390      2.364      0.019     156.633    1703.596
C(Time)[T.19:00]    4218.3318   2726.915      1.547      0.123   -1143.311    9579.975
Shiny               4189.6457    552.801      7.579      0.000    3102.733    5276.558
Rain                3045.7933    531.118      5.735      0.000    2001.512    4090.075
==============================================================================
Omnibus:                        6.722   Durbin-Watson:                   1.394
Prob(Omnibus):                  0.035   Jarque-Bera (JB):                7.447
Skew:                           0.205   Prob(JB):                       0.0241
Kurtosis:                       3.511   Cond. No.                     1.23e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.5e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [15]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [18]:
dfX = df.drop(["attendance"], axis=1)

In [19]:
dfX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 21 columns):
year       416 non-null int64
month      416 non-null int64
quarter    416 non-null int64
WeekDay    416 non-null object
Weekend    416 non-null int64
Home       416 non-null object
Result     416 non-null object
Away       416 non-null object
etc        416 non-null object
Time       416 non-null object
Park       416 non-null object
Shiny      416 non-null float64
Rain       416 non-null float64
Min_c      416 non-null float64
Max_c      416 non-null float64
NO2        416 non-null float64
O3         416 non-null float64
CO         416 non-null float64
SO2        416 non-null float64
PM10       416 non-null float64
PM25       416 non-null float64
dtypes: float64(10), int64(4), object(7)
memory usage: 68.4+ KB